### ISSUE TITLE
ne marque pas les amis / comptes

### ISSUE THREAD

**Issue by georgederr** [j4rj4r/BotTwitter#8]
ne semble pas baliser les comptes ... je n'obtiens pas d'erreurs, il ne balise pas, peut-être que je l'ai mal configuré? J'ai ajouté les comptes dans le fichier de configuration

**Comment by j4rj4r** [comment]
Salut,
j'ai pas compris ce que tu entends par '"baliser les comptes"
![screen_bot](https://user-images.githubusercontent.com/12416234/103168233-bdcf2a00-4831-11eb-9254-78bc1eee69c0.png)
Un petit screen de ce que doit faire le bot

**Comment by j4rj4r** [comment]
Si tu peux faire un petit screen de ce que tu as en afichage et de ta config (en floutant les keys api), je te dis ce qu'il va pas comme ca.

**Comment by georgederr** [comment]
désolé je parle anglais et utilise un traducteur.


Je voulais dire



Marquer des comptes lorsqu'un concours le demande

**Comment by georgederr** [comment]
Tag des comptes quand un concours le demande

**Comment by j4rj4r** [comment]
oh ok ! we can speak english ! 

I think the problem is here :
https://github.com/j4rj4r/BotTwitter/blob/60001c854b0a17509252ca3c770d1823f109f785/retweet_giveaway.py#L35-L38

With these regex you can detect if you need to tag or not but they are in french (sorry).
I will move this variable in the configuration file, I will soon translate the readme into English. If you see any translation errors in the script  (comment or print) please let me know. 😄

**Comment by georgederr** [comment]
Thanks! I think that worked. This is a really cool script by the way.

**Comment by georgederr** [comment]
> Thanks! I think that worked. This is a really cool script by the way.

`        regex_detect_tag = [r"\b(\w*INVITE(E|É)\w*)\b",
                            r"\b(\w*TAG(E|É)\w*)\b"
                            r"\b(\w*TAGGING\w*)\b",
                            r"\b(\w*MENTION(E|É)\w*)\b"]`

actually i don't think i changed it correctly?

**Comment by j4rj4r** [comment]
```
regex_detect_tag = [r"\b(\w*INVITE(E|É)\w*)\b", r"\b(\w*TAG(E|É|)\w*)\b",  r"\b(\w*TAGGING\w*)\b", r"\b(\w*MENTION(E|É)\w*)\b"]
```
Maybe like that
